
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { defineConfig, env } from "prisma/config";

// Prisma CLI 默认写入 ~/.cache/prisma，在某些环境会因为权限受限导致 generate 失败
const repoCacheRoot = path.resolve(process.cwd(), ".cache");
const prismaCacheDir = path.join(repoCacheRoot, "prisma");
fs.mkdirSync(prismaCacheDir, { recursive: true });

if (!process.env.XDG_CACHE_HOME) {
  process.env.XDG_CACHE_HOME = repoCacheRoot;
}
if (!process.env.CACHE_DIR) {
  process.env.CACHE_DIR = repoCacheRoot;
}
if (!process.env.PRISMA_CLI_CACHE_DIR) {
  process.env.PRISMA_CLI_CACHE_DIR = prismaCacheDir;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
